### ISSUE TITLE
About the whole model ?

### ISSUE THREAD

**Issue by maitetsu** [CalciferZh/minimal-body#1]
Hey, it is a very great work. By the way, is there any plan for releasing the whole model? What's more,  is there any plan for releasing the training code?

**Comment by CalciferZh** [comment]
We do plan to release the complete model but it may take some time. In the following, we will first release the IK part, then the hand part, and finally the full model. I'm not sure how long this may take.
We will not release the training code because that will take too much time.

**Comment by maitetsu** [comment]
Thank you for your timely reply.  I look forward to the whole model.
