### ISSUE TITLE
About light-weight human detector

### ISSUE THREAD

**Issue by Garfield-kh** [CalciferZh/minimal-body#2]
Very interesting model!
Since this model takes croped human as input, may I ask if there is any realtime human detector recommend that is light-weight to work with this model together?
Thank you~

**Comment by CalciferZh** [comment]
Hi, in practice you can use the 2D detection results of the model to obtain a bounding box for the next frame, so you only need to detect the body for the first frame to initialize everything. I guess a lot of repos can do this e.g. openpose.

**Comment by Garfield-kh** [comment]
Nice trick, got it, thank you! :P
